credentials:
  usernames:
    admin:
      name: Administrador
      password: '$2b$12$wO7m7J3aXYhXnU6a4.KRSeTwJtXkLE7/4vPXFYfJeZ9geGhDCIqum'

cookie:
  name: rips_app_cookie
  key: clave_ultrasecreta_123
  expiry_days: 30
