credentials:
  usernames:
    jeison:
      name: Jeison Eduardo
      password: 'pbkdf2:sha256:260000$9eU3MoEUpqKZ...'
      email: jeison@example.com
    usuario2:
      name: Usuario Demo
      password: 'pbkdf2:sha256:260000$0Oe7UdPaR2V...'
      email: demo@example.com

cookie:
  name: autenticacion_rips
  key: clave_super_secreta
  expiry_days: 7
