credentials:
  usernames:
    admin:
      name: Jeison Eduardo
      # ⬇️ Reemplaza este hash por el que generes con hash.py si quieres otra clave
      password: "$2b$12$Wz7KXlEisF3GJ6NwH/FfeOJnK7cfjGyYp3r0x6a1M4wB0RuPSm5/S"

cookie:
  name: my_cookie
  key: some_signature_key
  expiry_days: 3
