credentials:
  usernames:
    admin:
      name: Jeison Eduardo
      password: '$2b$12$LZXE4I7PKG7Qc4W8Yp6RuegUOZRGmnNgdr6rAZQs5u5LUYynFkkSO'  # Contraseña: 1012427400
      email: jeison@example.com

cookie:
  name: my_cookie
  key: some_signature_key
  expiry_days: 3
