credentials:
  usernames:
    user1:
      name: Jeison Eduardo
      password: 'pbkdf2:sha256:260000$y3f0Hk...'

cookie:
  name: my_cookie
  key: some_signature_key
  expiry_days: 3

preauthorized:
  emails:
    - jeison@email.com
