credentials:
  usernames:
    admin:
      name: Jeison Eduardo
      # ⬇️ Reemplaza este hash por el que generes con hash.py si quieres otra clave
      password: "$2b$12$PWb1bkGeHYRX2YInizX2P.4.4.fkxCScxAuZzLnz3mTwrFW.qqYEC"

cookie:
  name: my_cookie
  key: some_signature_key
  expiry_days: 3
