credentials:
  usernames:
    jeison:
      name: "Jeison Eduardo"
      password: "$2b$12$y7qjIpxh...."

    operador:
      name: "Operador de Facturación"
      password: "$2b$12$AFl9oH...."

    auditor:
      name: "Auditor Interno"
      password: "$2b$12$PQn3fz...."

    admin:
      name: "Administrador General"
      password: "$2b$12$KLvXhH...."

cookie:
  name: rips_cookie_demo
  key: clave_unica_demo
  expiry_days: 30

preauthorized:
  emails: []
