credentials:
  usernames:
    admin:
      name: Jeison Eduardo
      password: "$2b$12$86fzDlKfTo2ZpJlh9Wkj/uyccNwHcVttrCSWpY1H5E3lfjQJQ8EXy"

cookie:
  name: my_cookie
  key: some_signature_key
  expiry_days: 3
